### ISSUE TITLE
Identifying potential samples for miRNA analysis

### ISSUE THREAD

**Issue by sr320** [hputnam/project_juvenile_geoduck_OA#1]
![image](https://cloud.githubusercontent.com/assets/4442039/18393909/45af4f0a-766c-11e6-9be6-21151910c15a.png)

One option to consider is to start out with 
- Day 10 samples from ambient and super low.
- Day 135 samples from ambient and super low.

This would address  
- the basics of environmental stress / relation with transcription and methylation
- determine if miRNA patterns persist for 100+ days. 

@hputnam is this compatible with your processing?  and does this seem like a worthwhile effort and decent first endeavor to see if analyzing more samples is worth it.

**Comment by hputnam** [comment]
I think I would be inclined to also add time 0 depending on cost and if there is enough material for everything. It would add 4 more samples and give more information for temporal comparisons. Also depending on if it is time sensitive or not, we could wait for the RNAseq data to see how strong the responses are.... or just choose those points now based on the patterns in the phys data.

**Comment by sr320** [comment]
Makes sense - 
so ftr- a working option for further discussion would be 
- Day 0 (n=4)
- Day 10 samples from ambient (n=4) and super low (n=4).
- Day 135 samples from ambient (n=4)  and super low (n=4).

Total number of samples = 20

**Comment by hputnam** [comment]
sounds good! I should know what we have for time0 material soon. If we are thinking of using the TruSeq Small RNA Library Prep Kit, the protocol is optimized for 1 μg of total RNA input.

**Comment by hputnam** [comment]
Went with this [miRNA sample list](https://github.com/hputnam/project_juvenile_geoduck_OA/blob/master/Setup_Notes/miRNA_Samples.csv) and 2-3 reps for the end of common garden (29 July), Day 10 of second exposure (8 August) and Day 23 of second exposure (21 August). RNA quality of siphons will be tested and samples sequenced in Chile.
