### ISSUE TITLE
Pipeline Status

### ISSUE THREAD

**Issue by hputnam** [hputnam/project_juvenile_geoduck_OA#11]
@seanb80 (and @sr320 if you want) Can we chat next week about pipeline and analysis status?

**Comment by seanb80** [comment]
Sounds good to me. When works for you?

**Comment by sr320** [comment]
Monday? 10am PST?
I T,W,H are not good for me...

**Comment by seanb80** [comment]
I can make Monday at 10am PST work.

**Comment by hputnam** [comment]
Perfect. Monday Jan 30th at 10am Pacific, 1pm Eastern. Thanks!
