### ISSUE TITLE
Relatedness matrix for day 10 and day 0 groups

### ISSUE THREAD

**Issue by seanb80** [hputnam/project_juvenile_geoduck_OA#13]
Would it be appropriate to use relatedness data derived from the larger comparison (Day 0, 10, and 135) for the day 10 analysis, or should I recalculate the relatedness matrix using just Day 10 samples.

I believe the Fst values are calculated using row and column marginals, so more data is better, but I don't know if additional samples being included would affect things.

**Comment by hputnam** [comment]
I think they will have to be recalculated, as the samples were consumed at each time point and may not represent those selected at the next point.
