### ISSUE TITLE
Day 10 analysis

### ISSUE THREAD

**Issue by seanb80** [hputnam/project_juvenile_geoduck_OA#14]
IGV xml [here](http://owl.fish.washington.edu/scaphapoda/Sean/Day10/results/igv_session.xml)

RMD for the code [here](http://rpubs.com/seanb80/245101)

Raw data [here](http://owl.fish.washington.edu/scaphapoda/Sean/Day10/)

**Comment by sr320** [comment]
Sean - can you work on creating a narrative "lab notebook" entry each day?
Similar to those @ http://faculty.washington.edu/sr320/?page_id=246
(Sam's is always a good one to look to)

Can do at genefish.wordpress but I am open to discuss other options such as
GitHub (see Hollie's).
It should essentially be written for public. Also could imagine Hollie or I
having a quick look, and not really having any questions as everything is
there.
Thanks

**Comment by seanb80** [comment]
I wrote out this on gene fish, is it what you had in mind?

https://genefish.wordpress.com/2017/01/29/dmr-analysis-for-day-10-geoduck-samples/

**Comment by hputnam** [comment]
@sr320 @seanb80 After looking at the boxplots it seems we have several different patterns by treatment. What do you think about clustering the DML patterns and plotting by samples grouped by treatment similar to "Automatically Partitioning Genes into Expression Clusters" used in Trinity  (e.g., https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-Differential-Expression)

![expression_clusters](https://cloud.githubusercontent.com/assets/5198996/22723835/869f8134-ed8f-11e6-9de4-d1b260b9ac8c.jpg)

I think this could help us condense our box plots and give us patterning to interpret annotations.

**Comment by seanb80** [comment]
Count files located at
http://owl.fish.washington.edu/scaphapoda/Sean/count_files/

the 3/5/7/10x at the end of each file name signifies the different cutoff
levels used.

**Comment by hputnam** [comment]
Thanks @seanb80 I will try the clustering analysis.
