### ISSUE TITLE
Conversion Efficiency

### ISSUE THREAD

**Issue by hputnam** [hputnam/project_juvenile_geoduck_OA#15]
@seanb80 Can you point me toward the papers on issues in methylation in lambda?

**Comment by seanb80** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC356562/pdf/jvirol00275-0059.pdf
- Shows Methylation pattern in lambda grown in "normal" E. coli.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC246359/pdf/jbacter00349-0397.pdf
- Shows methylation patter in lambda based upon a DNA methylase mutant mec+/-

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC246359/pdf/jbacter00349-0397.pdf
- More stuff on mec+/- and methylation rates in lambda dna.

**Comment by hputnam** [comment]
Thank @seanb80
