### ISSUE TITLE
Meta: Adding Sean to repo 

### ISSUE THREAD

**Issue by sr320** [hputnam/project_juvenile_geoduck_OA#17]
Can we add Sean to this repo in a manner issues can be assigned to him?

![pic](http://eagle.fish.washington.edu/cnidarian/skitch/New_Issue_·_hputnam_project_juvenile_geoduck_OA_1E4B6A83.png)

**Comment by hputnam** [comment]
Yes, @seanb80 just needs to accept invitation to collaborate on repo.

**Comment by sr320** [comment]
Thanks!
