### ISSUE TITLE
Samples for DNA/RNA

### ISSUE THREAD

**Issue by sr320** [hputnam/project_juvenile_geoduck_OA#2]
Just wanted to confirm ...

this list of samples 
https://github.com/hputnam/project_juvenile_geoduck_OA/blob/master/Setup_Notes/Sample_List.csv

is everything you have for DNA/RNA and the plan is to do RNA-seq / MeDIP-BS on each sample you denote with `NGS`

thanks

**Comment by hputnam** [comment]
Yes. This is the master list for the juveniles and there is another for the larval samples. The NGS denotes the first choices for n=4 per treatment per time point
