### ISSUE TITLE
pH values that correspond to "ambient", "low", and "super.low"?

### ISSUE THREAD

**Issue by kubu4** [hputnam/project_juvenile_geoduck_OA#20]
@hputnam would you happen to have this info? Or, point me to where I can find this? @sr320 has asked me to submit all of the geoduck RNAseq to NCBI and I would like to add this info to the sample submission form.

**Comment by kubu4** [comment]
Never mind! Sorry. Completely forgot about the fact that there's a manuscript related to this project... :sun_with_face:

**Comment by hputnam** [comment]
Table S2. https://docs.google.com/document/d/10Wmr_ceODWreZfS8WPekvoBwD2xEqlq28iSitapHTHA/edit
