### ISSUE TITLE
Next Steps.. SK direction

### ISSUE THREAD

**Issue by sr320** [hputnam/project_juvenile_geoduck_OA#3]
Using this to try to find fit...
### Will edit to mark-up best priorities / mark-out

---

_No less than 10% of funds will be awarded to applications that develop and support
community-based bridge plans that enhance community resilience, from the perspectives of
both fishery working waterfront and living marine resource communities._

**Priority #1 –Marine Aquaculture**
Develop environmentally responsible marine aquaculture to create jobs in coastal
communities, produce healthful local seafood, revitalize working waterfronts, and support
traditional fishing communities. Projects should include, where feasible, participation of the
fishing communities, aquaculture communities, and the seafood industry. Projects that
provide training for fishermen and others in coastal communities in aquaculture production
methods are encouraged.
Projects sought should address at least one of the two topics below:
 Technology development and transfer: Develop, refine, or apply aquaculture
technologies that support aquaculture development. Projects that demonstrate aquaculture
technologies in operational settings such as through a pilot or commercial-scale project are
strongly encouraged.
 Tools for management: Provide tools to improve the understanding of the
environmental effects of aquaculture that will facilitate informed permit and management
decision-making.
Project examples could include but are not limited to:
• Demonstration of the feasibility of culturing marine species identified as potential or
suitable candidates for aquaculture including fish, molluscs, and macroalgae;
• Development of hatchery capacity and technologies;
• Investigation of ways to minimize negative interactions and maximize positive
interactions with living marine resources, especially protected and federally managed species
and their habitats; and
• Development or validation of genetics/escapes, disease transfer, habitat equivalency,
siting, socio-economic, or other models or tools for management of marine aquaculture.

---

**Priority #4 – Adapting to Climate Change and Other Long Term Ecosystem Change**
Projects sought should:
Assess the impact of climate change, ocean acidification, and other stressors on living
marine resources and the communities sustained by these resources.
Conduct research that better informs fishery managers on the predator-prey dynamic and the
role that density dependence plays on the short-term health of managed stocks.
Aid in the understanding and integration of all the interactions that marine and diadromous
fish have with predators, competitors, and prey species; other ocean uses e.g. energy projects
that can impact fishing, biological communities, and ecosystems; the complex interactions
between fisheries and their habitat; the effects of fishing on fish stocks and their habitat, or
for the seafood industry to understand, adapt and become more resilient to a change in
climate.
Research examples could include the following but are not limited to:
• Identify strategies for assisting fishing communities to adapt to potential effects of
climate change on fisheries.
• Assess how fishing communities have been impacted and have adapted to direct effects
of climate change, such as increased storms, and other natural events resulting in long term
trends.
• Develop stock assessment models that consider potential changes in fishery
performance and management effectiveness due to change in climate and ocean chemistry.
• Produce climate change and ocean chemistry forecasting models that incorporate fishery
production scenarios.
• Research on cumulative impacts that include climate change.
• Conduct vulnerability assessments to a changing climate at the fishing community level.

---

---

~~Priority #2 – Fishery Data Collection~~
Improve the cost -effectiveness, accuracy, timeliness, and methods for the collection,
reporting and dissemination of both fishery dependent data (commercial, non-commercial,
recreational and for--hire fisheries) and fishery independent data (surveys).
Projects sought should:
• Deliver cost effective and adaptive electronic tools to support electronic monitoring and
electronic reporting that will complement other fishery -dependent data collections, including
fishery observer and catch/effort monitoring programs;
• Track and integrate multiple fishery- dependent data streams such as vessel and dealer
reports for a single trip;
• Provide advanced fishery -independent sampling techniques to improve data collection
in otherwise inaccessible habitats, and improve current stock assessments by refining
estimates of population dynamics;
• Improve current sampling methods and/or introduce new methods to obtain fishery
-independent and fisheries dependent data for fisheries or locations that are not included or
not adequately covered in existing surveys; and
• Conduct studies to improve stock definitions and understanding of stock boundaries.

---

~~Priority #3 – Techniques for Reducing Bycatch and other Adverse Impacts~~
Projects sought should:
Develop and/or transfer selective commercial, non-commercial, and recreational fishing
gears or procedures that reduce bycatch impacts and other collateral effects.
Reduce impacts to protected species, candidate/species of concern, and fish stocks that are
overfished or where overfishing is occurring are encouraged.
Federal Funding Opportunity Page 6 of 38
Reduce or eliminate adverse interactions between fishing operations and non-targeted,
protected, or prohibited species, essential fish habitat (EFH); or critical habitat, including the
inadvertent take, capture, or destruction of such species or their habitats.
Improve the survivability of fish discarded or intentionally released and of protected species
released in fishing operations, including predation.
Investigate discard mortality in the commercial, non-commercial, and recreational fisheries
as a means to improve post release survival.
Research examples could include but are not limited to:
• Investigations on barotrauma;
• Investigations on post-release mortality and survival of protected species;
• Best practices in fish handling; and
• Quantitative techniques in estimating post--release survival of fish during recreational
fishing trips
• Reduce or eliminate impacts of fishing activity on essential fish habitat that adversely
affect the sustainability of the fishery.
Research examples could include but are not limited to:
• Development of gear technologies and/or changes to fishing practices to reduce the
destruction of habitat (such as coral and Special Areas of Conservation (SAC) habitats by
trawl, pot, anchor, or transiting), bycatch of sea turtles and sturgeon in bottom otter trawl or
gillnet gear;
• Development of new or improvement of existing gear modifications designed to reduce
incidental interactions between fishing gear and marine mammals, including studies to
investigate new gear which could effectively reduce serious injury and mortality of sea
turtles, small cetaceans, right whales and other large whales in the U.S. commercial fisheries
and through the development of entanglement mitigation gear;
• Improvement in the understanding of how interactions between fishing operations and
protected species occur, including interactions between trawl gear fisheries and marine
mammals, between fixed gear fisheries and large whales, and longline fisheries and small
cetaceans, sea turtles and seabirds.

---

---

~~Priority #5 – Promotion, Development and Marketing~~
Projects sought should:
Promote better business practices to increase product market value, such as increasing
market prices for commercial fish species by promoting business practices such as safe
handling (i.e., brining fish, using ozone boxes) and other value -added practices on vessels
and onshore to produce higher quality fish for sale. Projects may also include adoption of
technologies such as smart phones and tablets that support the fishing industry and the
public’s interest in the sustainability of marine fisheries by improving the traceability of
seafood from fishing vessels to consumers.
Develop collaborative and improved regional, national, and global public relations and
marketing opportunities that can position the U.S. domestic seafood industries to better
compete in globally competitive commodity markets, stabilize and maintain domestic fishing
cultures that have faltered due to suppressed prices, improve perception of and confidence in
U.S. domestic wild caught seafood products that may be impacted by natural or man-made
catastrophes, and improve fish prices. Fishermen will financially benefit from the
development of new domestic and foreign markets for abundant low -value and underutilized
species.
Develop projects that support the creation of new marketing opportunities.
Develop usable, value – added, fishery products from economic discards, byproducts of
processing, and introduced/nuisance species.
 Collect data on population dynamics, life histories, etc., of fish not currently under
Federal or Interstate fishery management, for the Regional Fishery Management
Councils/Interstate Marine Fisheries Commissions to determine the feasibility of developing
a new managed fishery that could provide additional fishing opportunity.
 Support development of new products from and markets for seafood processing waste
and low value species.
 Provide consumer and public outreach on the ecological and/or environmental impact,
including climate change related impacts such as production of greenhouse gasses, of
imported seafood products versus locally landed seafood products.

---

~~Priority #6 – Socio-Economic Research~~
Projects sought should:
Improve the understanding of the socioeconomic aspects of fisheries to increase information
on current and future consequences of management choices for use by decision makers and
stakeholders. The range of scope includes commercial, recreational, and subsistence fishing
and fishing -related businesses and fishing communities.
Research examples could include but are not limited to:
• Qualitative and quantitative baseline research on specific fishing communities;
• Cost- income data;
• Analyses of the socioeconomic impacts of specific management measures on certain
fisheries;
Federal Funding Opportunity Page 9 of 38
• Analyses of factors influencing demand for recreational fishing trips by anglers;
• Market analyses to determine factors that influence and trace the demand and supply of
specific seafood products, including imports; factors limiting fishing community
sustainability;
• Research into fishing community innovations in organization/governance, cooperatives,
marketing, risk-pooling, access to capital/permits/catch allocations, and other improvements
to promote sustainability;
• Data and evaluative models to assist decision makers in analyzing optimal allocations of
allowable biological catches

---

~~Priority #7 – Territorial Science~~
Projects sought should:
Improve the quality and quantity of fishery information from the U.S. territories covered by
the Magnuson-Stevens Act, including the territories of American Samoa, Guam, and the
U.S. Virgin Islands; and the Commonwealths of the Northern Mariana Islands and Puerto
Rico, that can be used for establishing, enhancing and monitoring Annual Catch Limits
(ACLs) and ecosystem-based information for Federal fisheries management in these
territories.
Project examples could include but are not limited to:
• Improve catch accountability by enhancing fishery statistics in each territory through a
variety of techniques, including expanded creel surveys, fish dealer sampling, and other
mechanisms;
• Expand fishery bio-sampling and analysis of bio-sampling data, including activities that
would include sampling shoreside and at fish dealers the species of fish most relevant for
management;
• Conduct fishery independent reef fish and bottomfish surveys;
• Build critical on -island capacity which could include building home-grown scientific
capacity by partnering with local academic institutions to engage students in the fishery
statistics data collection and bio-sampling life history studies.
• Build technical capabilities to conduct data collection and analysis in terms of analyzing
data for annual catch limits.

**Comment by sr320** [comment]
@hputnam so my first take is that it would need to fall into Priority 4- though nothing catching my eye in the verbiage that we can latch on to.

**Comment by hputnam** [comment]
@sr320 Yes, I agree priority 4. They have listed "Projects sought should:
Assess the impact of climate change, ocean acidification, and other stressors on living marine resources and the communities sustained by these resources." Here I am thinking about the linkage between preconditioning/hardening and potential fishery benefit of enhanced growth and stress tolerance and time to size maturity

Also under priority 1 " Development or validation of genetics/escapes, disease transfer, habitat equivalency, siting, socio-economic, or other models or tools for management of marine aquaculture." I think a single priority is recommended, but this could also be discussed...
